### ISSUE TITLE
Navigating around http://modularmoose.org/ doesn't change the URL in my browser

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/moosetechnology.github.io#1]
No, I think @sbragagnolo can help with this issue?

_Originally posted by @badetitou in https://github.com/moosetechnology/moose-wiki/issues/8#issuecomment-771430985_

**Comment by fuhrmanator** [comment]
I'm not sure what changed, but it looks OK to me today.

**Comment by badetitou** [comment]
@sbragagnolo worked a lot on it. Nice if it works now
