### ISSUE TITLE
Links are not obvious

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/moosetechnology.github.io#9]
Links look exactly like normal text if we do not hover them. Would be nice to differentiate them a little for accessibility.

**Comment by NicolasAnquetil** [comment]
YES !
some CSS work to do :-(

**Comment by badetitou** [comment]
I change the style, so they appear in blue. Maybe it is too blue. What is your opinion?

**Comment by NicolasAnquetil** [comment]
As long as we can see them, I don't really care.
Thank you
